config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :attempts, only: [:create, :index]
  resources :outgoings, only: [:create, :new]
  resources :posts, only: [:create, :new, :index, :show, :update]

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy', as: :signout
end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
end

app/models/outgoing.rb
class Outgoing < ActiveRecord::Base
  validates_presence_of :email, :name, :subject, :body
  validates :email, "MailValidation::Email" => true
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def verify
    redirect_to root_path unless session[:poster]
  end

end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController

  def create
    @attempt = Attempt.new(attempt_params)
    @attempt.ip = request.remote_ip
    @attempt.save!
    if @attempt.number == ENV['ACCESS_PIN']
      session[:access] = true
      session[:remaining] = 5
      flash[:success] = 'Access Granted.'
      redirect_to posts_path
    else
      flash[:alert] = "Access Denied. #{ActionController::Base.helpers.pluralize((session[:remaining] - 1), 'attempt')} remaining."
      session[:remaining] -= 1
      redirect_to root_path
    end
  end

  def index
    if session[:poster]
      @attempts = Attempt.order(:created_at).reverse_order.limit(50)
    else
      redirect_to root_path
    end
  end

  protected

  def attempt_params
    params.require(:attempt).permit(:number)
  end

end

app/controllers/outgoings_controller.rb
class OutgoingsController < ApplicationController
  before_action :verify

  def create
    @outgoing = Outgoing.new(outgoing_params)
    if @outgoing.save!
      OutgoingMailer.send_out(@outgoing).deliver
      flash[:success] = 'Message sent.'
      redirect_to new_post_path
    else
      flash[:error] = 'Unable to send.'
      render :new
    end
  end

  def new
    @outgoing = Outgoing.new
  end

  protected

  def outgoing_params
    params.require(:outgoing).permit(:name, :email, :subject, :body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @attempt = Attempt.new
    if session[:remaining].nil?
      session[:remaining] = 5
    elsif session[:remaining] == 0
      redirect_to 'http://venturicreative.com'
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :verify, only: [:create, :new, :show, :update]

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'Posted.'
      redirect_to posts_path
    else
      flash[:alert] = 'Error.'
      render :new
    end
  end

  def index
    @posts = Post.order(:created_at).reverse_order
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = 'Updated'
      redirect_to posts_path
    else
      flash[:alert] = 'Error.'
      render :show
    end
  end

  protected

  def post_params
    params.require(:post).permit(:body, :title)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if request.env['omniauth.auth']['uid'] == ENV['TWITTER_UID']
      session[:access] = true
      session[:poster] = true
      redirect_to new_post_path
    else
      session[:poster] = nil
      redirect_to root_path
    end
  end

  def destroy
    session[:poster] = nil
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attempts/index.html.haml
%br/
.row
  .small-12.columns
    %table{style: 'margin: auto;'}
      %tr
        %th Attempt
        %th IP Address
        %th Date/Time
      -@attempts.each do |attempt|
        %tr
          %td #{attempt.number}
          %td #{attempt.ip}
          %td #{attempt.created_at.to_formatted_s(:short)}
%br/

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title
      =content_for?(:title) ? yield(:title) : 'Venturi Creative'
    =stylesheet_link_tag    "application"
    =javascript_include_tag "vendor/modernizr"
    =csrf_meta_tags
    =google_webfonts_link_tag "Cinzel Decorative"
    =google_webfonts_link_tag "News Cycle"
  %body
    -unless flash.empty?
      .row
        .small-12.columns
          -flash.each do |name, msg|
            -if msg.is_a?(String)
              .alert-box{:class => name, "data-alert" => "", style: 'font-size: large;'}
                =content_tag :div, msg
                %a.close{:href => "#"} &times;
    -if session[:poster]
      .row
        .small-11.columns
          =yield
        .small-1.column
          %br/
          .icon-bar.large-vertical.four-up
            =link_to posts_path, class: 'item' do
              %i.fi-home
                .medium /posts
            =link_to attempts_path, class: 'item' do
              %i.fi-list-thumbnails
                .medium /attempts
            =link_to new_post_path, class: 'item' do
              %i.fi-pencil
                .medium /posts/new
            =link_to new_outgoing_path, class: 'item' do
              %i.fi-mail
                .medium /outgoings/new
            =link_to signout_path, class: 'item' do
              %i.fi-x
                .medium /signout
    -else
      =yield
    =javascript_include_tag "application"
    =yield :javascript

app/views/outgoings/new.html.haml
%br/
.row
  .small-10.small-centered.columns
    =simple_form_for @outgoing do |f|
      =f.input :name
      =f.input :email
      =f.input :subject
      =f.input :body, input_html: {style: 'height: 25em;'}
      %p.text-right
        =f.button :submit

app/views/pages/index.html.haml
=simple_form_for @attempt do |f|
  %br/
  .row.hide
    .small-10.medium-8.small-centered.columns
      =f.input :number, input_html: {maxlength: 12}
  .row
    .small-9.medium-6.large-3.small-offset-2.medium-offset-3.large-offset-4.columns
      .panel
        %h3.serif.text-center#display
          %em
            ready
  .row
    .small-3.medium-2.large-1.small-offset-2.medium-offset-3.large-offset-4.columns
      .button.expand.radius.serif#one 1
    .small-3.medium-2.large-1.columns
      .button.expand.radius.serif#two 2
    .small-3.medium-2.large-1.columns.end
      .button.expand.radius.serif#three 3
  .row
    .small-3.medium-2.large-1.small-offset-2.medium-offset-3.large-offset-4.columns
      .button.expand.radius.serif#four 4
    .small-3.medium-2.large-1.columns
      .button.expand.radius.serif#five 5
    .small-3.medium-2.large-1.columns.end
      .button.expand.radius.serif#six 6
  .row
    .small-3.medium-2.large-1.small-offset-2.medium-offset-3.large-offset-4.columns
      .button.expand.radius.serif#seven 7
    .small-3.medium-2.large-1.columns
      .button.expand.radius.serif#eight 8
    .small-3.medium-2.large-1.columns.end
      .button.expand.radius.serif#nine 9
  .row
    .small-3.medium-2.large-1.small-offset-2.medium-offset-3.large-offset-4.columns
      .button.expand.radius.serif#star *
    .small-3.medium-2.large-1.columns
      .button.expand.radius.serif#zero 0
    .small-3.medium-2.large-1.columns.end
      .button.expand.radius.serif#pound #

app/views/pages/posts.html.haml
%br/
.row
  .small-12.columns
    %h1.serif.text-center Welcome to Venturi Underground.
    %h1.text-center Watch this space for further developments.

app/views/posts/index.html.haml
%br/
.row
  .small-12.columns
    %h1.text-center.serif Welcome To Venturi Underground
    %p.text-center.serif
      %em I should really have a better tagline.
  %hr/
-@posts.each do |post|
  .row
    .small-10.small-centered.columns
      .panel
        %p.text-right
          %em Posted by Adam on #{post.created_at.to_formatted_s(:short)}
          -if session[:poster]
            =link_to post_path(post) do
              &nbsp;
              %i.fi-pencil
        %h1 #{post.title}
      %div
        =raw RedCloth.new(post.body).to_html
    %br/
    %hr/

app/views/posts/new.html.haml
%br/
.row
  .small-10.small-centered.columns
    =simple_form_for @post do |f|
      =f.input :title
      =f.textile_editor :body
      %p.text-right
        =f.button :submit
      =content_for :javascript do
        =textile_editor_initialize

app/views/posts/show.html.haml
%br/
.row
  .small-10.small-centered.columns
    =simple_form_for @post do |f|
      .row
        .small-10.columns
          =f.input :title
        .small-2.columns
          =f.input :active
      =f.textile_editor :body, style: 'height: 25em;'
      %p.text-right
        =f.button :submit
      =content_for :javascript do
        =textile_editor_initialize